mkgif_app/urls.py
from django.urls import path
from . import views

# App's name from inside the templates
app_name = 'mkgif_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('details/<int:pk>/', views.details, name='details'),
    path('delete_anim/<int:pk>/', views.delete_anim, name='delete_anim'),
]

mkgif_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mkgif_app.urls')),
    path('details/<int:pk>/', include('mkgif_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('django-rq/', include('django_rq.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mkgif_app/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User
import django_rq
from .utils import mk_gif_ffmpeg

class Animation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)

    def enqueue(self, params):
        django_rq.enqueue(mk_gif_ffmpeg, {
            'pk': self.pk,
            'params': params,
            }
        )

    # Showing readable name in admin page
    def __str__(self):
        return f"{self.name}"


class Image(models.Model):
    def image_path(self, filename):
        # Return a file path str, that we want to save the image to
        return f'{self.animation.pk}/{filename}'

    animation = models.ForeignKey('Animation', on_delete=models.CASCADE)
    # Take image_path function and upload the image's path to the file
    image = models.ImageField(upload_to=image_path)

    @property
    def media_url(self):
        return f'{ settings.MEDIA_URL }{ self.image }'

mkgif_app/views.py
from django.shortcuts import render, get_object_or_404
from .models import Animation, Image
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import reverse
from redis import Redis
import django_rq
from rq import Queue, Worker

@login_required
def index(request):
    # If we get a POST req, create an Animation obj instance
    if request.method == 'POST':
        # AFTER setting up user account
        anim = Animation.objects.create(name=request.POST['name'], user_id=request.user.id)

        # Loop through any images submitted
        for img in request.FILES.getlist('imgs'):
            # Save submitted images with the anim obj
            Image.objects.create(animation=anim, image=img)

    # Show a list of all Animation (without user)
    # anims = Animation.objects.all()

    # Show a list of all exisiting animations of the logged in user
    anims = Animation.objects.filter(user=request.user)
    context = {
            'anims': anims
            }
    return render(request, 'mkgif/index.html', context)

@login_required
def details(request, pk):
    anim = get_object_or_404(Animation, pk=pk)
    images = Image.objects.filter(animation=pk)

    # Use django_rq's Queue() to connect with Redis
    queue = Queue(connection=Redis())
    # Get Animation object with pk
    frames = Animation.objects.get(pk=pk)
    # Attach Animation obj to rqworker's .enqueue() method
    gif = frames.enqueue({})

    context = {
            'anim': anim,
            'images': images,
            'gif': gif,
            }
    return render(request, 'mkgif/details.html', context)

@login_required
def delete_anim(request, pk):
    #pk = request.POST.get('pk', 3)
    anim = get_object_or_404(Animation, pk=pk)
    anim.delete()

    # HttpResponseRedirect for staying on the same page
    return HttpResponseRedirect(reverse('mkgif_app:index'))

mkgif_app/templates/mkgif/details.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Make GIF</title>
    </head>
    <body>
        <h1>{{ anim.name }}</h1>
        <hr>

        <div>
            <p>Generated gif image: </p>
            <p>{{ anim.enqueue }}</p>
            <img src="/media/{{ anim.id }}/out.gif" />
        </div>
        <hr>

        {% for image in images %}
        <div><img src="{{ image.media_url }}" /></div>
        {% endfor %}
    </body>
</html>

mkgif_app/templates/mkgif/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/holiday.css@0.9.8" />
        <title>Make GIF</title>
    </head>
    <body>
        <header>
            <h1>Make GIF Animations</h1>
        </header>
        <nav>
            <ul>
                <li><a href="{% url 'mkgif_app:index' %}">Home</a></li>
                <li>
                    <span>{{ user }}</span>
                    <ul>
                        <li><a href="{% url 'logout' %}">Logout</a></li>
                    </ul>
                    </span>
                </li>
            </ul>
        </nav>
        <main>
            <p>My GIF Animations:</p>
            <table>
                {% for anim in anims %}
                <tr>
                <form action="{% url 'mkgif_app:delete_anim' anim.pk %}" method="POST">
                    {% csrf_token %}
                 <td>{{ anim.pk }}</td>
                <td>
                     <a href="{% url 'mkgif_app:details' anim.pk %}">{{ anim.name }}</a>
                </td>
                <td><button type="submit">Delete</button></td>
                </form>
                </tr>
                {% endfor %}
            </table>
            <hr>
            <form action="{% url 'mkgif_app:index' %}" method="POST" enctype="multipart/form-data">
                <fieldset>
                    <legend><label>Add New GIF Animation</label></legend>
                    {% csrf_token %}
                    <input name="name" type="text" placeholder="Animation name">
                    <input name="imgs" type="file" multiple>
                    <button type="submit">Submit</button>
                </fieldset>
            </form>
        </main>
    </body>
</html>